---
- name: Start all VMs that were initially started
  scale_computing.hypercore.vm_params:
    vm_name: "{{ item.vm_name }}"
    power_state: start
    # TODO ignore error if VM is not present, or check first if VM is present
  when: item.power_state == 'started'
  loop: "{{ version_update_single_node_restart_vms.records }}"
  register: version_update_single_node_vm_start_result

- name: Show restart results
  ansible.builtin.debug:
    var: version_update_single_node_vm_start_result
